name: ci-timeseries-inspector

on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest

    env:
      VERSION: ${{ github.sha }}
      HARBOR_REGISTRY_URL: ${{ secrets.HARBOR_REGISTRY_URL }}
      HARBOR_REGISTRY_USERNAME: ${{ secrets.HARBOR_REGISTRY_USERNAME }}
      HARBOR_REGISTRY_PASSWORD: ${{ secrets.HARBOR_REGISTRY_PASSWORD }}

    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: docker build -t $HARBOR_REGISTRY_URL/baeda/services/timeseries-inspector:$VERSION --file ./Dockerfile .
      - name: Publish
        run: |
          echo $HARBOR_REGISTRY_PASSWORD | docker login $HARBOR_REGISTRY_URL --username $HARBOR_REGISTRY_USERNAME --password-stdin
          docker push $HARBOR_REGISTRY_URL/baeda/services/timeseries-inspector:$VERSION